/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rpc_remote_exec_ML_server_startSession.h"
#include "rpc_remote_exec_ML_server_runExecFunction.h"
#include "rpc_remote_exec_ML_server_getExecFunction.h"
/*
u_long maxCurrentID=0;


u_long *
startsession_1_svc(void *argp, struct svc_req *rqstp)
{
	static u_long  result;

	maxCurrentID++;
	result=maxCurrentID;

	return &result;
}

runExecStructResponse *
runexecfunction_1_svc(runExecStructRequest *argp, struct svc_req *rqstp)
{
	static runExecStructResponse  result;
	list* node;

	switch(argp->packageType){
		case INPUT_START:
		printf("INPUT_START\n");
		addToList(argp->ID);
		result.lastCorrectPackageNR=0;
		//usuwanie ewentualnie istenijacego pliku;
		break;
		case INPUT_FUNCTION:
		printf("INPUT_FUNCTION\n");
		node = searchInList(argp->ID);
		if(node->inputpacketnr==argp->packageNR-1){
			node->inputpacketnr=argp->packageNR;
			//zapisywanie do pliku?
		}
		result.lastCorrectPackageNR=node->inputpacketnr;
		break;
		case INPUT_INPUT:
		printf("INPUT_INPUT\n");
		node = searchInList(argp->ID);
		if(node->inputpacketnr==argp->packageNR-1){
			node->inputpacketnr=argp->packageNR;
			//zapisywanie do pliku?
		}
		result.lastCorrectPackageNR=node->inputpacketnr;
		break;
		case INPUT_END:
		printf("INPUT_END\n");
		node = searchInList(argp->ID);
		if(node->inputpacketnr==argp->packageNR-1){
			node->inputpacketnr=argp->packageNR;
			//zapisywanie do pliku?
		}
		result.lastCorrectPackageNR=node->inputpacketnr;
		break;
	}

	
	return &result;
}

getExecStructResponse *
getexecfunction_1_svc(getExecStructRequest *argp, struct svc_req *rqstp)
{
	static getExecStructResponse  result;

	/*
	 * insert server code here


	return &result;
}*/
