/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rpc_remote_exec_ML_server_startSession.h"
#include "rpc_remote_exec_ML_server_runExecFunction.h"
#include "rpc_remote_exec_ML_server_getExecFunction.h"
