/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC_REMOTE_EXEC_ML_H_RPCGEN
#define _RPC_REMOTE_EXEC_ML_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define INPUT_START 1
#define INPUT_FUNCTION 2
#define INPUT_INPUT 3
#define INPUT_END 4

struct runExecStructRequest {
	int dataSize;
	u_long ID;
	int packetAmount;
	int packageNR;
	int packageType;
	char *data;
};
typedef struct runExecStructRequest runExecStructRequest;

struct runExecStructResponse {
	int lastCorrectPackageNR;
};
typedef struct runExecStructResponse runExecStructResponse;

struct getExecStructRequest {
	u_long ID;
	int packageNR;
};
typedef struct getExecStructRequest getExecStructRequest;

struct getExecStructResponse {
	int dataSize;
	int packetAmount;
	int packageNR;
	int packageType;
	char *data;
};
typedef struct getExecStructResponse getExecStructResponse;

#define rpcRemoteExecML 0x22334455
#define rpcRemoteExecMLVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define startSession 1
extern  u_long * startsession_1(void *, CLIENT *);
extern  u_long * startsession_1_svc(void *, struct svc_req *);
#define runExecFunction 2
extern  runExecStructResponse * runexecfunction_1(runExecStructRequest *, CLIENT *);
extern  runExecStructResponse * runexecfunction_1_svc(runExecStructRequest *, struct svc_req *);
#define getExecFunction 3
extern  getExecStructResponse * getexecfunction_1(getExecStructRequest *, CLIENT *);
extern  getExecStructResponse * getexecfunction_1_svc(getExecStructRequest *, struct svc_req *);
extern int rpcremoteexecml_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define startSession 1
extern  u_long * startsession_1();
extern  u_long * startsession_1_svc();
#define runExecFunction 2
extern  runExecStructResponse * runexecfunction_1();
extern  runExecStructResponse * runexecfunction_1_svc();
#define getExecFunction 3
extern  getExecStructResponse * getexecfunction_1();
extern  getExecStructResponse * getexecfunction_1_svc();
extern int rpcremoteexecml_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_runExecStructRequest (XDR *, runExecStructRequest*);
extern  bool_t xdr_runExecStructResponse (XDR *, runExecStructResponse*);
extern  bool_t xdr_getExecStructRequest (XDR *, getExecStructRequest*);
extern  bool_t xdr_getExecStructResponse (XDR *, getExecStructResponse*);

#else /* K&R C */
extern bool_t xdr_runExecStructRequest ();
extern bool_t xdr_runExecStructResponse ();
extern bool_t xdr_getExecStructRequest ();
extern bool_t xdr_getExecStructResponse ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPC_REMOTE_EXEC_ML_H_RPCGEN */
