/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rpc_remote_exec_ML.h"
#include "rpc_remote_exec_ML_client_startSession.h"
#include "rpc_remote_exec_ML_client_runExecFunction.h"
#include "rpc_remote_exec_ML_def.h"
#include "rpc_remote_exec_ML_client_getExecFunction.h"

CLIENT* createClient(char *host){
	CLIENT *clnt;
	clnt = clnt_create (host, rpcRemoteExecML, rpcRemoteExecMLVERS, "udp");
		if (clnt == NULL) {
			clnt_pcreateerror (host);
			exit (1);
		}
	return clnt;
}
void destroyClient(CLIENT *clnt){
	clnt_destroy (clnt);
}



int main (int argc, char *argv[])
{
	int code=0; // Zwracany kod wykonywanego programu
	char *host; // Address servera
	CLIENT *clnt; 
	u_long session_ID; // Id klienta
	char *functionToExec; // nazwa funkcji do wykonania
	int packagerNR=0;

	int sendBufferSize=1024;

	if (argc < 3) {
		printf ("usage: %s server_host function_to_exec\n", argv[0]);
		exit (1);
	}
	if( argc>3){
		sendBufferSize=strtol(argv[3], NULL, 10);
	}
	host = argv[1];
	functionToExec = argv[2];
	//rpcremoteexecml_1 (host);

	clnt=createClient(host);

	session_ID=startsession(clnt); // Otrzymanie Id od servera

	sendFunctionToRun(clnt,session_ID,functionToExec,&packagerNR,sendBufferSize); // Wykonanie funkcji na serverze
	code=getresultFromRemoteFuntion(clnt,session_ID,&packagerNR); // Uzyskanie wyniku wykonanej funkcji

	destroyClient(clnt);

	exit (code);
}
