/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rpc_remote_exec_ML.h"
#include "rpc_remote_exec_ML_client_startSession.h"
#include "rpc_remote_exec_ML_client_runExecFunction.h"

CLIENT* createClient(char *host){
	CLIENT *clnt;
	clnt = clnt_create (host, rpcRemoteExecML, rpcRemoteExecMLVERS, "udp");
		if (clnt == NULL) {
			clnt_pcreateerror (host);
			exit (1);
		}
	return clnt;
}
void destroyClient(CLIENT *clnt){
	clnt_destroy (clnt);
}

void
rpcremoteexecml_1(char *host)
{
	CLIENT *clnt;
	u_long  *result_1;
	char *startsession_1_arg;
	runExecStructResponse  *result_2;
	runExecStructRequest  runexecfunction_1_arg;
	getExecStructResponse  *result_3;
	getExecStructRequest  getexecfunction_1_arg;

#ifndef	DEBUG
		clnt = clnt_create (host, rpcRemoteExecML, rpcRemoteExecMLVERS, "udp");
		if (clnt == NULL) {
			clnt_pcreateerror (host);
			exit (1);
		}
#endif	/* DEBUG */

	result_1 = startsession_1((void*)&startsession_1_arg, clnt);
	if (result_1 == (u_long *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	printf("otrzymany id - %lu\n",*result_1);

	/*result_2 = runexecfunction_1(&runexecfunction_1_arg, clnt);
	if (result_2 == (runExecStructResponse *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = getexecfunction_1(&getexecfunction_1_arg, clnt);
	if (result_3 == (getExecStructResponse *) NULL) {
		clnt_perror (clnt, "call failed");
	}*/
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	CLIENT *clnt;
	u_long session_ID;
	char *functionToExec;

	int sendBufferSize=1024;

	if (argc < 3) {
		printf ("usage: %s server_host function_to_exec\n", argv[0]);
		exit (1);
	}
	if( argc>3){
		sendBufferSize=strtol(argv[3], NULL, 10);
	}
	host = argv[1];
	functionToExec = argv[2];
	//rpcremoteexecml_1 (host);

	clnt=createClient(host);

	session_ID=startsession(clnt);

	sendFunctionToRun(clnt,session_ID,functionToExec,sendBufferSize);

	destroyClient(clnt);

exit (0);
}
